/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    'portfolio-projects': PortfolioProject;
    'blog-posts': BlogPost;
    reviews: Review;
    faqs: Faq;
    'contact-requests': ContactRequest;
    'contact-attachments': ContactAttachment;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'portfolio-projects': PortfolioProjectsSelect<false> | PortfolioProjectsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'contact-requests': ContactRequestsSelect<false> | ContactRequestsSelect<true>;
    'contact-attachments': ContactAttachmentsSelect<false> | ContactAttachmentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    homepage: Homepage;
    'static-pages': StaticPage;
    'legal-pages': LegalPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'static-pages': StaticPagesSelect<false> | StaticPagesSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  category?: ('blog' | 'portfolio-before' | 'portfolio-after' | 'general') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  /**
   * Identificator intern (relații, seed). Nu se schimbă după publicare.
   */
  slug: string;
  /**
   * Slug public pentru URL /servicii/{pageSlug}
   */
  pageSlug: string;
  icon:
    | 'Hammer'
    | 'PaintBrush'
    | 'Wrench'
    | 'ComputerTower'
    | 'Shield'
    | 'Car'
    | 'Lightning'
    | 'CheckCircle'
    | 'Phone'
    | 'Clock';
  shortDescription?: string | null;
  description: string;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  intro?: string | null;
  whenNeededTitle?: string | null;
  whenNeededItems?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  processTitle?: string | null;
  processSteps?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  ctaTitle?: string | null;
  ctaDescription?: string | null;
  ctaPrimaryLabel?: string | null;
  ctaSecondaryLabel?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  ogImage?: (number | null) | Media;
  featured?: boolean | null;
  active?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-projects".
 */
export interface PortfolioProject {
  id: number;
  title: string;
  slug: string;
  /**
   * ID numeric vechi pentru redirecturi (/portofoliu/1 → slug)
   */
  legacyId?: string | null;
  description: string;
  services?: (number | Service)[] | null;
  beforeImage?: (number | null) | Media;
  afterImage?: (number | null) | Media;
  /**
   * Fallback temporar pentru imagini externe la seed
   */
  legacyBeforeImageUrl?: string | null;
  /**
   * Fallback temporar pentru imagini externe la seed
   */
  legacyAfterImageUrl?: string | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  duration?: string | null;
  vehicleBrand?: string | null;
  vehicleModel?: string | null;
  featured?: boolean | null;
  publishedAt?: string | null;
  order?: number | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  /**
   * Imagine pentru share. Dacă e goală, se folosește OG-ul implicit pentru proiecte portofoliu din Setări site, apoi imaginea Open Graph implicită.
   */
  ogImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  /**
   * ID numeric vechi pentru redirecturi (/blog/1 → slug)
   */
  legacyId?: string | null;
  excerpt: string;
  coverImage?: (number | null) | Media;
  /**
   * Fallback temporar pentru imagini externe la seed
   */
  legacyCoverImageUrl?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Articole importate din data.ts — randate ca fallback dacă body lipsește
   */
  legacyMarkdown?: string | null;
  publishedAt?: string | null;
  readTime?: string | null;
  category?: ('guides' | 'tips' | 'insurance' | 'maintenance' | 'general') | null;
  featured?: boolean | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  ogImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  /**
   * Cheie stabilă pentru seed idempotent
   */
  seedKey?: string | null;
  /**
   * Folosește numele public din sursă sau inițiale dacă persoana a cerut anonimizarea.
   */
  name: string;
  rating: number;
  /**
   * Lasă gol dacă evaluarea nu are comentariu public. Nu inventa un testimonial.
   */
  text?: string | null;
  /**
   * Bifat automat când există text real; folosit pentru filtre și sortare.
   */
  hasComment?: boolean | null;
  date: string;
  service?: (number | null) | Service;
  /**
   * Etichetă liberă dacă relationship-ul lipsește (ex. la seed)
   */
  serviceLabel?: string | null;
  /**
   * Locul din care poate fi verificat feedbackul.
   */
  source?: ('google' | 'facebook' | 'direct' | 'other') | null;
  /**
   * Obligatoriu pentru Google, Facebook sau altă sursă publică. Poate fi linkul profilului dacă nu există link direct către recenzie.
   */
  sourceUrl?: string | null;
  /**
   * Bifează doar pentru feedback primit direct, după ce clientul a acceptat publicarea.
   */
  consentConfirmed?: boolean | null;
  /**
   * Confirmă că ratingul, autorul și textul corespund unei surse reale sau feedbackului autorizat.
   */
  verified?: boolean | null;
  verifiedAt?: string | null;
  /**
   * Devine publică numai dacă este bifată și „Sursă verificată”.
   */
  approved?: boolean | null;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  /**
   * Cheie stabilă pentru seed idempotent
   */
  seedKey?: string | null;
  question: string;
  answer: string;
  category?: ('services' | 'insurance' | 'pricing' | 'general') | null;
  published?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-requests".
 */
export interface ContactRequest {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  carBrand?: string | null;
  licensePlate?: string | null;
  service?: (number | null) | Service;
  /**
   * Tip serviciu (text liber dacă relationship lipsește)
   */
  serviceType?: string | null;
  message?: string | null;
  gdprConsent: boolean;
  /**
   * Fotografii private atașate la cerere.
   */
  photos?: (number | ContactAttachment)[] | null;
  /**
   * Număr de fotografii (pentru listare rapidă).
   */
  photoCount?: number | null;
  status: 'new' | 'contacted' | 'scheduled' | 'closed' | 'spam';
  source?: string | null;
  submittedAt: string;
  ip?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Fotografii private din formularul de contact. Nu sunt publice.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-attachments".
 */
export interface ContactAttachment {
  id: number;
  contactRequest?: (number | null) | ContactRequest;
  originalFilename?: string | null;
  sizeBytes?: number | null;
  uploadedAt: string;
  /**
   * Dată estimată pentru ștergere conform politicii de retenție.
   */
  retentionUntil?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'portfolio-projects';
        value: number | PortfolioProject;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'contact-requests';
        value: number | ContactRequest;
      } | null)
    | ({
        relationTo: 'contact-attachments';
        value: number | ContactAttachment;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  pageSlug?: T;
  icon?: T;
  shortDescription?: T;
  description?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  heroTitle?: T;
  heroSubtitle?: T;
  intro?: T;
  whenNeededTitle?: T;
  whenNeededItems?:
    | T
    | {
        item?: T;
        id?: T;
      };
  processTitle?: T;
  processSteps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  ctaTitle?: T;
  ctaDescription?: T;
  ctaPrimaryLabel?: T;
  ctaSecondaryLabel?: T;
  seoTitle?: T;
  seoDescription?: T;
  ogImage?: T;
  featured?: T;
  active?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-projects_select".
 */
export interface PortfolioProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  legacyId?: T;
  description?: T;
  services?: T;
  beforeImage?: T;
  afterImage?: T;
  legacyBeforeImageUrl?: T;
  legacyAfterImageUrl?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  duration?: T;
  vehicleBrand?: T;
  vehicleModel?: T;
  featured?: T;
  publishedAt?: T;
  order?: T;
  seoTitle?: T;
  seoDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  legacyId?: T;
  excerpt?: T;
  coverImage?: T;
  legacyCoverImageUrl?: T;
  body?: T;
  legacyMarkdown?: T;
  publishedAt?: T;
  readTime?: T;
  category?: T;
  featured?: T;
  seoTitle?: T;
  seoDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  seedKey?: T;
  name?: T;
  rating?: T;
  text?: T;
  hasComment?: T;
  date?: T;
  service?: T;
  serviceLabel?: T;
  source?: T;
  sourceUrl?: T;
  consentConfirmed?: T;
  verified?: T;
  verifiedAt?: T;
  approved?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  seedKey?: T;
  question?: T;
  answer?: T;
  category?: T;
  published?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-requests_select".
 */
export interface ContactRequestsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  carBrand?: T;
  licensePlate?: T;
  service?: T;
  serviceType?: T;
  message?: T;
  gdprConsent?: T;
  photos?: T;
  photoCount?: T;
  status?: T;
  source?: T;
  submittedAt?: T;
  ip?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-attachments_select".
 */
export interface ContactAttachmentsSelect<T extends boolean = true> {
  contactRequest?: T;
  originalFilename?: T;
  sizeBytes?: T;
  uploadedAt?: T;
  retentionUntil?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  tagline?: string | null;
  phone: string;
  /**
   * Format internațional fără +, ex: 40760686384
   */
  whatsappNumber?: string | null;
  whatsappMessage?: string | null;
  email?: string | null;
  address?: string | null;
  schedule?: string | null;
  googleMapsUrl?: string | null;
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
  };
  facebook?: string | null;
  instagram?: string | null;
  /**
   * Ex: https://carfixpaint.ro
   */
  canonicalDomain?: string | null;
  /**
   * Imagine folosită la share pe rețele sociale când o pagină nu are imagine OG proprie.
   */
  defaultOgImage?: (number | null) | Media;
  /**
   * Folosită pe paginile de proiect dacă proiectul nu are og:image propriu. Dacă lipsește, se folosește imaginea Open Graph implicită.
   */
  portfolioDefaultOgImage?: (number | null) | Media;
  ctaPhoneLabel?: string | null;
  ctaQuoteLabel?: string | null;
  /**
   * Inițiale afișate în logo
   */
  logoAbbreviation?: string | null;
  footerDescription?: string | null;
  footerServices?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  navigationItems?:
    | {
        path: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  heroBadge?: string | null;
  heroTitle?: string | null;
  heroAccentText?: string | null;
  heroDescription?: string | null;
  heroCtaPhoneLabel?: string | null;
  heroCtaQuoteLabel?: string | null;
  benefits?:
    | {
        icon:
          | 'Hammer'
          | 'PaintBrush'
          | 'Wrench'
          | 'ComputerTower'
          | 'Shield'
          | 'Car'
          | 'Lightning'
          | 'CheckCircle'
          | 'Phone'
          | 'Clock';
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  servicesSectionTitle?: string | null;
  servicesSectionSubtitle?: string | null;
  portfolioSectionTitle?: string | null;
  reviewsSectionTitle?: string | null;
  servicesLimit?: number | null;
  portfolioLimit?: number | null;
  reviewsLimit?: number | null;
  damageProcessTitle?: string | null;
  damageProcessSteps?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  finalCtaTitle?: string | null;
  finalCtaDescription?: string | null;
  finalCtaButtonLabel?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  seoKeywords?: string | null;
  ogTitle?: string | null;
  ogDescription?: string | null;
  /**
   * Imagine afișată la share pe rețele sociale. Dacă e goală, se folosește imaginea implicită din Setări site.
   */
  ogImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "static-pages".
 */
export interface StaticPage {
  id: number;
  servicii: {
    pageTitle: string;
    pageSubtitle?: string | null;
    seoTitle?: string | null;
    seoDescription?: string | null;
    seoKeywords?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    /**
     * Imagine afișată la share pe rețele sociale. Dacă e goală, se folosește imaginea implicită din Setări site.
     */
    ogImage?: (number | null) | Media;
  };
  daune: {
    pageTitle: string;
    pageSubtitle?: string | null;
    highlights?:
      | {
          icon:
            | 'Hammer'
            | 'PaintBrush'
            | 'Wrench'
            | 'ComputerTower'
            | 'Shield'
            | 'Car'
            | 'Lightning'
            | 'CheckCircle'
            | 'Phone'
            | 'Clock';
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    processTitle?: string | null;
    processSteps?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    ctaTitle?: string | null;
    ctaDescription?: string | null;
    ctaContactLabel?: string | null;
    seoTitle?: string | null;
    seoDescription?: string | null;
    seoKeywords?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    /**
     * Imagine afișată la share pe rețele sociale. Dacă e goală, se folosește imaginea implicită din Setări site.
     */
    ogImage?: (number | null) | Media;
  };
  portofoliu: {
    pageTitle: string;
    pageSubtitle?: string | null;
    seoTitle?: string | null;
    seoDescription?: string | null;
    seoKeywords?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    /**
     * Imagine afișată la share pe rețele sociale. Dacă e goală, se folosește imaginea implicită din Setări site.
     */
    ogImage?: (number | null) | Media;
  };
  despre: {
    pageTitle: string;
    intro?: string | null;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    whyTitle?: string | null;
    whyItems?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    missionTitle?: string | null;
    missionText?: string | null;
    valuesTitle?: string | null;
    valuesContent?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    seoTitle?: string | null;
    seoDescription?: string | null;
    seoKeywords?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    /**
     * Imagine afișată la share pe rețele sociale. Dacă e goală, se folosește imaginea implicită din Setări site.
     */
    ogImage?: (number | null) | Media;
  };
  recenzii: {
    pageTitle: string;
    pageSubtitle?: string | null;
    seoTitle?: string | null;
    seoDescription?: string | null;
    seoKeywords?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    /**
     * Imagine afișată la share pe rețele sociale. Dacă e goală, se folosește imaginea implicită din Setări site.
     */
    ogImage?: (number | null) | Media;
  };
  faq: {
    pageTitle: string;
    pageSubtitle?: string | null;
    seoTitle?: string | null;
    seoDescription?: string | null;
    seoKeywords?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    /**
     * Imagine afișată la share pe rețele sociale. Dacă e goală, se folosește imaginea implicită din Setări site.
     */
    ogImage?: (number | null) | Media;
  };
  blog: {
    pageTitle: string;
    pageSubtitle?: string | null;
    seoTitle?: string | null;
    seoDescription?: string | null;
    seoKeywords?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    /**
     * Imagine afișată la share pe rețele sociale. Dacă e goală, se folosește imaginea implicită din Setări site.
     */
    ogImage?: (number | null) | Media;
  };
  contact: {
    pageTitle: string;
    pageSubtitle?: string | null;
    contactCardTitle?: string | null;
    fastResponseTitle?: string | null;
    fastResponseText?: string | null;
    seoTitle?: string | null;
    seoDescription?: string | null;
    seoKeywords?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    /**
     * Imagine afișată la share pe rețele sociale. Dacă e goală, se folosește imaginea implicită din Setări site.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  privacyTitle?: string | null;
  privacyContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  privacySeoTitle?: string | null;
  privacySeoDescription?: string | null;
  privacyOgImage?: (number | null) | Media;
  cookiesTitle?: string | null;
  cookiesContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cookiesSeoTitle?: string | null;
  cookiesSeoDescription?: string | null;
  cookiesOgImage?: (number | null) | Media;
  termsTitle?: string | null;
  termsContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  termsSeoTitle?: string | null;
  termsSeoDescription?: string | null;
  termsOgImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  tagline?: T;
  phone?: T;
  whatsappNumber?: T;
  whatsappMessage?: T;
  email?: T;
  address?: T;
  schedule?: T;
  googleMapsUrl?: T;
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  facebook?: T;
  instagram?: T;
  canonicalDomain?: T;
  defaultOgImage?: T;
  portfolioDefaultOgImage?: T;
  ctaPhoneLabel?: T;
  ctaQuoteLabel?: T;
  logoAbbreviation?: T;
  footerDescription?: T;
  footerServices?:
    | T
    | {
        label?: T;
        id?: T;
      };
  navigationItems?:
    | T
    | {
        path?: T;
        label?: T;
        id?: T;
      };
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroBadge?: T;
  heroTitle?: T;
  heroAccentText?: T;
  heroDescription?: T;
  heroCtaPhoneLabel?: T;
  heroCtaQuoteLabel?: T;
  benefits?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  servicesSectionTitle?: T;
  servicesSectionSubtitle?: T;
  portfolioSectionTitle?: T;
  reviewsSectionTitle?: T;
  servicesLimit?: T;
  portfolioLimit?: T;
  reviewsLimit?: T;
  damageProcessTitle?: T;
  damageProcessSteps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  finalCtaTitle?: T;
  finalCtaDescription?: T;
  finalCtaButtonLabel?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoKeywords?: T;
  ogTitle?: T;
  ogDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "static-pages_select".
 */
export interface StaticPagesSelect<T extends boolean = true> {
  servicii?:
    | T
    | {
        pageTitle?: T;
        pageSubtitle?: T;
        seoTitle?: T;
        seoDescription?: T;
        seoKeywords?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
      };
  daune?:
    | T
    | {
        pageTitle?: T;
        pageSubtitle?: T;
        highlights?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
        processTitle?: T;
        processSteps?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        ctaTitle?: T;
        ctaDescription?: T;
        ctaContactLabel?: T;
        seoTitle?: T;
        seoDescription?: T;
        seoKeywords?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
      };
  portofoliu?:
    | T
    | {
        pageTitle?: T;
        pageSubtitle?: T;
        seoTitle?: T;
        seoDescription?: T;
        seoKeywords?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
      };
  despre?:
    | T
    | {
        pageTitle?: T;
        intro?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        whyTitle?: T;
        whyItems?:
          | T
          | {
              item?: T;
              id?: T;
            };
        missionTitle?: T;
        missionText?: T;
        valuesTitle?: T;
        valuesContent?: T;
        seoTitle?: T;
        seoDescription?: T;
        seoKeywords?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
      };
  recenzii?:
    | T
    | {
        pageTitle?: T;
        pageSubtitle?: T;
        seoTitle?: T;
        seoDescription?: T;
        seoKeywords?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
      };
  faq?:
    | T
    | {
        pageTitle?: T;
        pageSubtitle?: T;
        seoTitle?: T;
        seoDescription?: T;
        seoKeywords?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
      };
  blog?:
    | T
    | {
        pageTitle?: T;
        pageSubtitle?: T;
        seoTitle?: T;
        seoDescription?: T;
        seoKeywords?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
      };
  contact?:
    | T
    | {
        pageTitle?: T;
        pageSubtitle?: T;
        contactCardTitle?: T;
        fastResponseTitle?: T;
        fastResponseText?: T;
        seoTitle?: T;
        seoDescription?: T;
        seoKeywords?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  privacyTitle?: T;
  privacyContent?: T;
  privacySeoTitle?: T;
  privacySeoDescription?: T;
  privacyOgImage?: T;
  cookiesTitle?: T;
  cookiesContent?: T;
  cookiesSeoTitle?: T;
  cookiesSeoDescription?: T;
  cookiesOgImage?: T;
  termsTitle?: T;
  termsContent?: T;
  termsSeoTitle?: T;
  termsSeoDescription?: T;
  termsOgImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}